import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC', // Slightly warmer background
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 6,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 1.5,
    elevation: 2,
  },
  topBarSpacer: {
    minWidth: 80,
  },
  feedHeading: {
    flex: 1,
    paddingRight: 10,
  },
  pageTitle: {
    color: '#0F172A', // Darker for better contrast
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  pageSubtitle: {
    color: '#64748B', // Better contrast than gray
    marginTop: 2,
    fontSize: 12,
    fontWeight: '500',
  },
  feedTabs: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    paddingHorizontal: 16,
    marginBottom: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 1,
    elevation: 1,
  },
  feedTabButton: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 6,
    paddingBottom: 2,
  },
  feedTabText: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '600',
    paddingBottom: 8,
  },
  feedTabTextActive: {
    color: '#1D4ED8',
  },
  feedTabIndicator: {
    height: 2,
    width: 40,
    borderRadius: 1,
    backgroundColor: '#1D4ED8',
    marginTop: -2,
  },
  logoutButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  logoutText: {
    color: '#475569',
    fontWeight: '600',
    fontSize: 12,
  },
  composerContainer: {
    marginBottom: 8,
    marginHorizontal: 16,
  },
  composerCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 4,
    marginBottom: 16,
  },
  composerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  avatarCircle: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: '#1D4ED8',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  avatarInitial: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 20,
  },
  composerTitle: {
    flex: 1,
  },
  composerLabel: {
    color: '#0F172A',
    fontSize: 17,
    fontWeight: '800',
  },
  composerSubLabel: {
    color: '#475569',
    marginTop: 4,
    fontSize: 13,
    lineHeight: 18,
  },
  inputIconWrap: {
    height: 48,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  inputWithIcon: {
    flex: 1,
    height: '100%',
    color: '#0F172A',
    fontSize: 15,
    fontWeight: '600',
    outlineWidth: 0,
    outlineStyle: 'none',
    outlineColor: 'transparent',
  },
  textAreaWrap: {
    minHeight: 108,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  textAreaIcon: {
    marginLeft: 14,
    marginTop: 16,
  },
  textArea: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    color: '#0F172A',
    minHeight: 104,
    paddingTop: 14,
    paddingRight: 14,
    paddingBottom: 14,
    paddingLeft: 10,
    fontSize: 15,
    fontWeight: '600',
    textAlignVertical: 'top',
    outlineWidth: 0,
    outlineStyle: 'none',
    outlineColor: 'transparent',
  },
  anonymousToggleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#F8FAFC',
    marginBottom: 12,
  },
  anonymousLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  anonymousToggleLabel: {
    color: '#0F172A',
    fontSize: 14,
    fontWeight: '600',
  },
  anonymousToggleButton: {
    paddingVertical: 7,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#F8FAFC',
  },
  anonymousToggleButtonActive: {
    borderColor: '#14B8A6',
    backgroundColor: '#D1FAE5',
  },
  anonymousToggleButtonText: {
    color: '#475569',
    fontSize: 13,
    fontWeight: '600',
  },
  anonymousToggleButtonTextActive: {
    color: '#14B8A6',
  },
  input: {
    backgroundColor: '#F8FAFC',
    color: '#0F172A',
    height: 52,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    paddingHorizontal: 16,
    fontSize: 15,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 2,
    elevation: 1,
  },
  titleErrorText: {
    color: '#DC2626',
    fontSize: 13,
    marginBottom: 12,
    marginTop: -6,
    fontWeight: '500',
  },
  infoText: {
    color: '#6B7280',
    marginBottom: 12,
    fontSize: 13,
  },
  postButton: {
    backgroundColor: '#1D4ED8',
    height: 38,
    minWidth: 84,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    shadowColor: '#1D4ED8',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  postButtonDisabled: {
    opacity: 0.6,
    shadowOpacity: 0.1,
  },
  postButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 14,
  },
  secondaryButton: {
    minWidth: 76,
    height: 38,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  secondaryButtonText: {
    color: '#1D4ED8',
    fontWeight: '700',
    fontSize: 14,
  },
  createPostTitle: {
    color: '#111827',
    fontSize: 17,
    fontWeight: '800',
  },
  submitErrorBanner: {
    backgroundColor: '#FEF2F2',
    borderBottomWidth: 1,
    borderBottomColor: '#FECACA',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  submitErrorBannerText: {
    color: '#B91C1C',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  permissionGateCard: {
    marginTop: 20,
    marginHorizontal: 16,
    borderRadius: 24,
    padding: 22,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
  },
  permissionGateEyebrow: {
    color: '#9CA3AF',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 10,
  },
  permissionGateTitle: {
    color: '#111827',
    fontSize: 22,
    fontWeight: '800',
    lineHeight: 28,
    marginBottom: 10,
  },
  permissionGateBody: {
    color: '#6B7280',
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 18,
  },
  permissionChecklist: {
    marginBottom: 22,
  },
  permissionChecklistItem: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 14,
    padding: 14,
    backgroundColor: '#F9FAFB',
    marginBottom: 10,
  },
  permissionChecklistLabel: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 4,
  },
  permissionChecklistText: {
    color: '#6B7280',
    fontSize: 13,
    lineHeight: 19,
  },
  permissionActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  permissionErrorText: {
    color: '#EF4444',
    fontSize: 13,
    marginBottom: 10,
  },
  createPostContainer: {
    flex: 1,
  },
  createPostScroll: {
    flex: 1,
  },
  createPostScrollContent: {
    paddingBottom: 40,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  feedList: {
    paddingTop: 4,
    paddingBottom: 100,
  },
  fabButton: {
    position: 'absolute',
    right: 20,
    bottom: 24,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#1D4ED8',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#1D4ED8',
    shadowOpacity: 0.35,
    shadowOffset: { width: 0, height: 5 },
    shadowRadius: 12,
    elevation: 7,
  },
  fabButtonText: {
    color: '#FFFFFF',
    fontSize: 32,
    fontWeight: '300',
    lineHeight: 36,
    marginTop: -2,
  },
  feedCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginHorizontal: 16,
  },
  feedHeader: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  avatarCircleSmall: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#DCFCE7',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarInitialSmall: {
    color: '#14B8A6',
    fontWeight: '800',
  },
  feedHeaderText: {
    flex: 1,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  authorName: {
    color: '#111827',
    fontWeight: '700',
    marginRight: 8,
  },
  authorHandle: {
    color: '#9CA3AF',
    marginRight: 8,
  },
  timeStamp: {
    color: '#9CA3AF',
  },
  locationLabel: {
    color: '#6B7280',
    marginTop: 2,
  },
  feedContent: {
    color: '#374151',
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 14,
  },
  tagRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  statusChip: {
    borderWidth: 1,
    borderColor: '#86EFAC',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    marginRight: 10,
    marginBottom: 8,
    backgroundColor: '#F0FDF4',
  },
  statusText: {
    color: '#14B8A6',
    fontWeight: '700',
    fontSize: 12,
  },
  cardAction: {
    color: '#9CA3AF',
    marginRight: 18,
    fontSize: 13,
    marginBottom: 8,
  },
  imageUploadSection: {
    marginTop: 8,
  },
  imageUploadHeader: {
    marginBottom: 10,
  },
  imageUploadTitle: {
    color: '#0F172A',
    fontSize: 15,
    fontWeight: '800',
  },
  imageUploadHelper: {
    color: '#475569',
    fontSize: 12,
    marginTop: 3,
  },
  imagePickerButton: {
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#BBF7D0',
    backgroundColor: '#F0FDF4',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
  },
  imageSourceRow: {
    gap: 10,
  },
  imagePickerButtonText: {
  color: '#1D4ED8',
    fontSize: 13,
    fontWeight: '800',
  },
  imagePreviewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  imagePreviewCard: {
    width: '48%',
    marginBottom: 12,
  },
  imagePreview: {
    width: '100%',
    height: 120,
    borderRadius: 12,
    backgroundColor: '#E5E7EB',
    marginBottom: 8,
  },
  imagePreviewLabel: {
    color: '#6B7280',
    fontSize: 12,
  },
  removeImageButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(0,0,0,0.55)',
  },
  removeImageButtonText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '600',
  },
  imageErrorText: {
    color: '#EF4444',
    fontSize: 13,
    marginTop: 2,
  },
  locationCard: {
    borderWidth: 1,
    borderColor: '#BBF7D0',
    borderRadius: 12,
    padding: 12,
    backgroundColor: '#F0FDF4',
    marginBottom: 12,
  },
  locationHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 10,
  },
  locationCardTitle: {
    color: '#14B8A6',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 4,
  },
  locationCardText: {
    color: '#334155',
    fontSize: 13,
    lineHeight: 19,
    maxWidth: 280,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginBottom: 4,
  },
  locationCardHelper: {
    color: '#9CA3AF',
    fontSize: 12,
    marginTop: 6,
  },
  locationCardWarning: {
    color: '#D97706',
    fontSize: 12,
    marginTop: 6,
  },
  locationCardError: {
    color: '#EF4444',
    fontSize: 12,
    marginTop: 6,
  },
  locationActionRow: {
    flexDirection: 'column',
    gap: 10,
    marginTop: 12,
  },
  detectLocationButton: {
    flex: 1,
    minHeight: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#86EFAC',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 10,
  },
  detectLocationButtonText: {
    color: '#1D4ED8',
    fontSize: 12,
    fontWeight: '700',
  },
  locationRefreshButton: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationRefreshButtonText: {
    color: '#14B8A6',
    fontSize: 12,
    fontWeight: '700',
  },
  previewCard: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 14,
    padding: 14,
    backgroundColor: '#FFFFFF',
  },
  previewHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  previewIcon: {
    width: 34,
    height: 34,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#14B8A6',
  },
  previewTitle: {
    color: '#0F172A',
    fontSize: 15,
    fontWeight: '800',
  },
  previewHelper: {
    color: '#64748B',
    fontSize: 12,
    lineHeight: 18,
  },
  previewImage: {
    width: '100%',
    height: 180,
    borderRadius: 12,
    backgroundColor: '#E5E7EB',
    marginBottom: 12,
  },
  previewEmptyState: {
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
    borderRadius: 12,
    height: 110,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 18,
    marginBottom: 12,
    backgroundColor: '#FFFFFF',
  },
  previewEmptyStateText: {
    color: '#9CA3AF',
    fontSize: 13,
    textAlign: 'center',
  },
  previewLocationLabel: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  previewLocationText: {
    color: '#0F172A',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  emptyStateTitle: {
    color: '#334155',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 10,
    textAlign: 'center',
  },
  emptyStateText: {
    color: '#64748B',
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
  },
});

export default styles;
