import { StyleSheet, Platform } from 'react-native';


const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
    paddingTop: Platform.OS === 'android' ? 16 : 24,
    paddingHorizontal: 16,
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  topBarSpacer: {
    minWidth: 96,
  },
  feedHeading: {
    flex: 1,
    paddingRight: 10,
  },
  pageTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '800',
  },
  pageSubtitle: {
    color: '#A3A3A3',
    marginTop: 2,
    fontSize: 12,
  },
  feedTabs: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#18181B',
    marginBottom: 8,
  },
  feedTabButton: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 4,
    paddingBottom: 8,
  },
  feedTabText: {
    color: '#71717A',
    fontSize: 14,
    fontWeight: '600',
  },
  feedTabTextActive: {
    color: '#FFFFFF',
  },
  feedTabIndicator: {
    marginTop: 6,
    width: 44,
    height: 3,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
  },
  logoutButton: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
  },
  logoutText: {
    color: '#000000',
    fontWeight: '700',
  },
  composerContainer: {
    marginBottom: 14,
  },
  composerCard: {
    backgroundColor: '#000000',
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: '#27272A',
    shadowColor: '#000',
    shadowOpacity: 0.22,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 18,
    elevation: 5,
  },
  composerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  avatarCircle: {
    width: 46,
    height: 46,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarInitial: {
    color: '#000000',
    fontWeight: '800',
    fontSize: 18,
  },
  composerTitle: {
    flex: 1,
  },
  composerLabel: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  composerSubLabel: {
    color: '#A3A3A3',
    marginTop: 4,
    fontSize: 13,
  },
  textArea: {
    backgroundColor: '#000000',
    color: '#FFFFFF',
    minHeight: 96,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#3F3F46',
    padding: 14,
    fontSize: 15,
    textAlignVertical: 'top',
    marginBottom: 12,
  },
  input: {
    backgroundColor: '#000000',
    color: '#FFFFFF',
    height: 46,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#3F3F46',
    paddingHorizontal: 14,
    fontSize: 15,
    marginBottom: 12,
  },
  infoText: {
    color: '#D4D4D8',
    marginBottom: 12,
    fontSize: 14,
  },
  postButton: {
    backgroundColor: '#FFFFFF',
    height: 48,
    minWidth: 96,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  postButtonDisabled: {
    opacity: 0.7,
  },
  postButtonText: {
    color: '#000000',
    fontWeight: '700',
    fontSize: 16,
  },
  secondaryButton: {
    minWidth: 96,
    height: 48,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#3F3F46',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000000',
  },
  secondaryButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 16,
  },
  createPostTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
  },
  permissionGateCard: {
    marginTop: 22,
    borderRadius: 28,
    padding: 22,
    borderWidth: 1,
    borderColor: '#27272A',
    backgroundColor: '#050505',
  },
  permissionGateEyebrow: {
    color: '#A3A3A3',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 10,
  },
  permissionGateTitle: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '800',
    lineHeight: 30,
    marginBottom: 10,
  },
  permissionGateBody: {
    color: '#D4D4D8',
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 18,
  },
  permissionChecklist: {
    marginBottom: 22,
  },
  permissionChecklistItem: {
    borderWidth: 1,
    borderColor: '#27272A',
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#090909',
    marginBottom: 10,
  },
  permissionChecklistLabel: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 4,
  },
  permissionChecklistText: {
    color: '#A3A3A3',
    fontSize: 13,
    lineHeight: 19,
  },
  permissionActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  permissionErrorText: {
    color: '#F87171',
    fontSize: 13,
    marginBottom: 10,
  },
  createPostContainer: {
    flex: 1,
  },
  createPostScroll: {
    flex: 1,
  },
  createPostScrollContent: {
    paddingBottom: 40,
  },
  feedList: {
    paddingBottom: 128,
  },
  fabButton: {
    position: 'absolute',
    right: 20,
    bottom: 22,
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.24,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 18,
    elevation: 8,
  },
  fabButtonText: {
    color: '#000000',
    fontSize: 28,
    fontWeight: '700',
    lineHeight: 30,
  },
  feedCard: {
    backgroundColor: '#0F172A',
    borderRadius: 24,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#1E293B',
  },
  feedHeader: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  avatarCircleSmall: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#334155',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarInitialSmall: {
    color: '#EFF6FF',
    fontWeight: '800',
  },
  feedHeaderText: {
    flex: 1,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  authorName: {
    color: '#FFFFFF',
    fontWeight: '700',
    marginRight: 8,
  },
  authorHandle: {
    color: '#A3A3A3',
    marginRight: 8,
  },
  timeStamp: {
    color: '#A3A3A3',
  },
  locationLabel: {
    color: '#D4D4D8',
    marginTop: 2,
  },
  feedContent: {
    color: '#FFFFFF',
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 14,
  },
  tagRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  statusChip: {
    borderWidth: 1,
    borderColor: '#52525B',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    marginRight: 10,
    marginBottom: 8,
  },
  statusText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 12,
  },
  cardAction: {
    color: '#A3A3A3',
    marginRight: 18,
    fontSize: 13,
    marginBottom: 8,
  },
  imageUploadSection: {
    marginTop: 8,
  },
  imageUploadHeader: {
    marginBottom: 10,
  },
  imageUploadTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  imageUploadHelper: {
    color: '#A3A3A3',
    fontSize: 12,
    marginTop: 4,
  },
  imagePickerButton: {
    height: 46,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#3F3F46',
    backgroundColor: '#090909',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  imageSourceRow: {
    gap: 10,
  },
  imagePickerButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  imagePreviewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  imagePreviewCard: {
    width: '48%',
    marginBottom: 12,
  },
  imagePreview: {
    width: '100%',
    height: 120,
    borderRadius: 14,
    backgroundColor: '#111111',
    marginBottom: 8,
  },
  imagePreviewLabel: {
    color: '#A3A3A3',
    fontSize: 12,
  },
  removeImageButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
    borderWidth: 1,
    borderColor: '#3F3F46',
  },
  removeImageButtonText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '600',
  },
  imageErrorText: {
    color: '#F87171',
    fontSize: 13,
    marginTop: 2,
  },
  locationCard: {
    borderWidth: 1,
    borderColor: '#27272A',
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#070707',
    marginBottom: 12,
  },
  locationHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 10,
  },
  locationCardTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 4,
  },
  locationCardText: {
    color: '#D4D4D8',
    fontSize: 13,
    lineHeight: 19,
    maxWidth: 220,
  },
  locationCardHelper: {
    color: '#A3A3A3',
    fontSize: 12,
    marginTop: 8,
  },
  locationCardWarning: {
    color: '#FBBF24',
    fontSize: 12,
    marginTop: 8,
  },
  locationCardError: {
    color: '#F87171',
    fontSize: 12,
    marginTop: 8,
  },
  locationRefreshButton: {
    borderWidth: 1,
    borderColor: '#3F3F46',
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#111111',
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationRefreshButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  previewCard: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#27272A',
    borderRadius: 20,
    padding: 16,
    backgroundColor: '#070707',
  },
  previewTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 4,
  },
  previewHelper: {
    color: '#A3A3A3',
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 12,
  },
  previewImage: {
    width: '100%',
    height: 180,
    borderRadius: 16,
    backgroundColor: '#111111',
    marginBottom: 12,
  },
  previewEmptyState: {
    borderWidth: 1,
    borderColor: '#27272A',
    borderStyle: 'dashed',
    borderRadius: 16,
    height: 120,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 18,
    marginBottom: 12,
  },
  previewEmptyStateText: {
    color: '#71717A',
    fontSize: 13,
    textAlign: 'center',
  },
  previewLocationLabel: {
    color: '#A3A3A3',
    fontSize: 12,
    marginBottom: 4,
  },
  previewLocationText: {
    color: '#FFFFFF',
    fontSize: 13,
    lineHeight: 19,
  },
  emptyState: {
    borderWidth: 1,
    borderColor: '#27272A',
    borderRadius: 20,
    padding: 18,
    backgroundColor: '#050505',
  },
  emptyStateTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 6,
  },
  emptyStateText: {
    color: '#A3A3A3',
    fontSize: 13,
    lineHeight: 19,
  },
});

export default styles;
